---
# tasks file for Dell-Networking.dellos-dns
 - name: "Provisioning DNS configuration for dellos9"
   dellos9_config:
      src: dellos9_dns.j2
      provider: "{{ cli }}"
   when: ansible_net_os_name == "dellos9"
#   notify: save config os9
